# Generated by Django 4.0.4 on 2022-05-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('birth', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=4, max_digits=4)),
                ('male', models.BooleanField()),
                ('level', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('dep', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
