# Generated by Django 4.0.4 on 2022-05-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_students_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('mail', models.CharField(max_length=255, primary_key=True, serialize=False, unique=b'I01\n')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
