# Generated by Django 4.0.4 on 2022-05-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='level',
            field=models.IntegerField(),
        ),
    ]
